### ISSUE TITLE
Does not support XLSX files

### ISSUE THREAD

**Issue by danhetrick** [paceaux/xlsx-to-json#4]
Despite the title of this project, it does not seem to support XLSX files. At least, that's what the program told me when I ran it.

**Comment by paceaux** [comment]
The library that I was using for this stopped supporting xlsx. I've since updated this to use a different library, as well as adding some modicum of error handling. 

I'm sure you've moved on to other utilities by this point, I'm terribly sorry for the inconvenience. this was the first thing I ever wrote in Python; didn't really have a clue what I was doing.
